apiVersion: apps/v1
kind: Deployment
metadata:
  name: st-main-listen
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: st-main-listen
        image: st-main-listen
